FROM ubuntu:bionic

RUN apt-get update && apt-get install -qq locales \
    && locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

ENV USER root
ENV LOGNAME root

RUN apt-get update && apt-get install -qq \
      tree \
    && rm -rf /var/lib/apt/lists/*