FROM ubuntu:bionic

RUN apt-get update && apt-get install -qq locales \
    && locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

ENV USER root
ENV LOGNAME root

RUN apt-get update && apt-get install -qq \
      tree \
RUN apt-get install curl && apt-get install unzip \
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
RUN unzip awscliv2.zip \
RUN ./aws/install \
    && rm -rf /var/lib/apt/lists/*
